import type {
  Estimate,
  Invitation,
  Membership,
  Organization,
  PortalRequest,
  Project,
  RequestEvent,
  RequestMessage,
  UserProfile,
} from "./types";

export const SEED_ORGANIZATIONS: Organization[] = [
  {
    id: "org-apex-legal",
    name: "Apex Legal Partners",
    slug: "apex-legal",
    domain: "apexlegal.example.com",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "org-beacon-wealth",
    name: "Beacon Wealth Advisors",
    slug: "beacon-wealth",
    domain: "beaconwealth.example.com",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-15T10:00:00.000Z",
  },
];

export const SEED_PROJECTS: Project[] = [
  {
    id: "proj-apex-web",
    organizationId: "org-apex-legal",
    name: "Apex Legal Website",
    domain: "apexlegal.example.com",
    status: "active",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "proj-apex-portal",
    organizationId: "org-apex-legal",
    name: "Client Intake Portal",
    domain: "intake.apexlegal.example.com",
    status: "active",
    createdAt: "2026-08-05T10:00:00.000Z",
    updatedAt: "2026-08-05T10:00:00.000Z",
  },
  {
    id: "proj-beacon-web",
    organizationId: "org-beacon-wealth",
    name: "Beacon Wealth Advisory Hub",
    domain: "beaconwealth.example.com",
    status: "active",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-15T10:00:00.000Z",
  },
];

export const SEED_USERS: UserProfile[] = [
  // Client Owner (Apex Legal)
  {
    uid: "user-sarah-apex",
    email: "sarah.jenkins@apexlegal.example.com",
    displayName: "Sarah Jenkins",
    currentOrganizationId: "org-apex-legal",
    isStaff: false,
    isStudioAdmin: false,
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  // Client Member (Apex Legal)
  {
    uid: "user-marcus-apex",
    email: "marcus.vance@apexlegal.example.com",
    displayName: "Marcus Vance",
    currentOrganizationId: "org-apex-legal",
    isStaff: false,
    isStudioAdmin: false,
    createdAt: "2026-08-02T10:00:00.000Z",
    updatedAt: "2026-08-02T10:00:00.000Z",
  },
  // Client Owner (Beacon Wealth - Organization B)
  {
    uid: "user-elena-beacon",
    email: "elena.rostova@beaconwealth.example.com",
    displayName: "Elena Rostova",
    currentOrganizationId: "org-beacon-wealth",
    isStaff: false,
    isStudioAdmin: false,
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-15T10:00:00.000Z",
  },
  // Studio Staff
  {
    uid: "user-alex-staff",
    email: "alex.morales@chromapages.com",
    displayName: "Alex Morales",
    currentOrganizationId: "org-apex-legal",
    isStaff: true,
    isStudioAdmin: false,
    mfaEnrolled: true,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-01T10:00:00.000Z",
  },
  // Studio Admin
  {
    uid: "user-devin-admin",
    email: "devin.cross@chromapages.com",
    displayName: "Devin Cross",
    currentOrganizationId: "org-apex-legal",
    isStaff: true,
    isStudioAdmin: true,
    mfaEnrolled: true,
    createdAt: "2026-07-01T10:00:00.000Z",
    updatedAt: "2026-07-01T10:00:00.000Z",
  },
];

export const SEED_MEMBERSHIPS: Membership[] = [
  {
    id: "org-apex-legal_user-sarah-apex",
    organizationId: "org-apex-legal",
    userId: "user-sarah-apex",
    email: "sarah.jenkins@apexlegal.example.com",
    displayName: "Sarah Jenkins",
    role: "client_owner",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
  {
    id: "org-apex-legal_user-marcus-apex",
    organizationId: "org-apex-legal",
    userId: "user-marcus-apex",
    email: "marcus.vance@apexlegal.example.com",
    displayName: "Marcus Vance",
    role: "client_member",
    createdAt: "2026-08-02T10:00:00.000Z",
    updatedAt: "2026-08-02T10:00:00.000Z",
  },
  {
    id: "org-beacon-wealth_user-elena-beacon",
    organizationId: "org-beacon-wealth",
    userId: "user-elena-beacon",
    email: "elena.rostova@beaconwealth.example.com",
    displayName: "Elena Rostova",
    role: "client_owner",
    createdAt: "2026-08-15T10:00:00.000Z",
    updatedAt: "2026-08-15T10:00:00.000Z",
  },
  {
    id: "org-apex-legal_user-alex-staff",
    organizationId: "org-apex-legal",
    userId: "user-alex-staff",
    email: "alex.morales@chromapages.com",
    displayName: "Alex Morales",
    role: "staff",
    createdAt: "2026-08-01T10:00:00.000Z",
    updatedAt: "2026-08-01T10:00:00.000Z",
  },
];

export const SEED_INVITATIONS: Invitation[] = [
  {
    id: "inv-apex-claire",
    tokenHash: "hash_token_apex_demo_123",
    tokenPlain: "apex-demo-token-123",
    organizationId: "org-apex-legal",
    organizationName: "Apex Legal Partners",
    invitedEmail: "claire.tanaka@apexlegal.example.com",
    role: "client_member",
    createdBy: "user-sarah-apex",
    createdByName: "Sarah Jenkins",
    expiresAt: "2026-10-01T00:00:00.000Z",
    revoked: false,
    createdAt: "2026-09-01T10:00:00.000Z",
  },
];

export const SEED_REQUESTS: PortalRequest[] = [
  {
    id: "req-apex-101",
    referenceNumber: "REQ-1001",
    organizationId: "org-apex-legal",
    projectId: "proj-apex-web",
    projectName: "Apex Legal Website",
    title: "Partner Bio Page Layout Update for New Tax Practice",
    description: "We are launching our new corporate tax advisory practice next month and need to add 3 partner bios with case highlight carousels.",
    category: "content",
    status: "in_progress",
    priority: "normal",
    businessImpact: "high",
    affectedUrl: "https://apexlegal.example.com/team",
    desiredDate: "2026-09-20",
    scheduledDate: "2026-09-18",
    coverage: "included",
    requesterId: "user-sarah-apex",
    requesterName: "Sarah Jenkins",
    requesterEmail: "sarah.jenkins@apexlegal.example.com",
    assigneeId: "user-alex-staff",
    assigneeName: "Alex Morales",
    attachments: [],
    version: 1,
    createdAt: "2026-09-02T14:30:00.000Z",
    updatedAt: "2026-09-04T09:15:00.000Z",
  },
  {
    id: "req-apex-102",
    referenceNumber: "REQ-1002",
    organizationId: "org-apex-legal",
    projectId: "proj-apex-portal",
    projectName: "Client Intake Portal",
    title: "Mobile Form Validation Error on Document Upload",
    description: "Clients on iOS Safari report that clicking 'Choose Document' fails to open the native camera roll picker.",
    category: "bug",
    status: "in_review",
    priority: "urgent",
    businessImpact: "critical",
    affectedUrl: "https://intake.apexlegal.example.com/step-3",
    bugDetails: {
      expectedBehavior: "Camera roll and file picker open when tap upload button.",
      actualBehavior: "Button highlights but picker never opens on iOS 18.",
      reproductionSteps: "1. Open intake on iPhone.\n2. Proceed to step 3.\n3. Tap Upload Document.",
      deviceBrowser: "iOS 18 / Safari 18.0",
    },
    desiredDate: "2026-09-10",
    coverage: "unreviewed",
    requesterId: "user-marcus-apex",
    requesterName: "Marcus Vance",
    requesterEmail: "marcus.vance@apexlegal.example.com",
    attachments: [],
    version: 1,
    createdAt: "2026-09-05T11:00:00.000Z",
    updatedAt: "2026-09-05T11:00:00.000Z",
  },
  {
    id: "req-apex-103",
    referenceNumber: "REQ-1003",
    organizationId: "org-apex-legal",
    projectId: "proj-apex-web",
    projectName: "Apex Legal Website",
    title: "Quarterly Insights Report Interactive Data Visualization",
    description: "Interactive chart module showing litigation settlement benchmarks for Q3 report.",
    category: "feature",
    status: "awaiting_approval",
    priority: "high",
    businessImpact: "medium",
    coverage: "additional_estimate",
    desiredDate: "2026-09-30",
    requesterId: "user-sarah-apex",
    requesterName: "Sarah Jenkins",
    requesterEmail: "sarah.jenkins@apexlegal.example.com",
    assigneeId: "user-alex-staff",
    assigneeName: "Alex Morales",
    currentEstimateVersion: 1,
    attachments: [],
    version: 1,
    createdAt: "2026-09-01T16:00:00.000Z",
    updatedAt: "2026-09-06T14:20:00.000Z",
  },
  // Beacon Wealth Request (Organization B - strictly isolated from Apex Legal!)
  {
    id: "req-beacon-201",
    referenceNumber: "REQ-2001",
    organizationId: "org-beacon-wealth",
    projectId: "proj-beacon-web",
    projectName: "Beacon Wealth Advisory Hub",
    title: "Retirement Calculator Micro-App Integration",
    description: "Embed our vetted retirement planning widget into the private advisory hub.",
    category: "feature",
    status: "in_review",
    priority: "high",
    businessImpact: "high",
    coverage: "unreviewed",
    requesterId: "user-elena-beacon",
    requesterName: "Elena Rostova",
    requesterEmail: "elena.rostova@beaconwealth.example.com",
    attachments: [],
    version: 1,
    createdAt: "2026-09-04T10:00:00.000Z",
    updatedAt: "2026-09-04T10:00:00.000Z",
  },
];

export const SEED_ESTIMATES: Estimate[] = [
  {
    id: "est-req-apex-103-v1",
    requestId: "req-apex-103",
    organizationId: "org-apex-legal",
    version: 1,
    scopeSummary: "Custom SVG/Canvas interactive benchmark visualizer with CSV data source and accessible table fallback.",
    amountUsd: 2400,
    estimatedHours: 16,
    notes: "Includes mobile responsive layout, screen-reader data table, and print stylesheet.",
    createdBy: "user-alex-staff",
    createdByName: "Alex Morales",
    createdAt: "2026-09-06T14:20:00.000Z",
  },
];

export const SEED_MESSAGES: RequestMessage[] = [
  {
    id: "msg-101-1",
    requestId: "req-apex-101",
    organizationId: "org-apex-legal",
    authorId: "user-sarah-apex",
    authorName: "Sarah Jenkins",
    authorRole: "client_owner",
    body: "Hi team, we've finalized the biographies and headshots in Google Drive. Let us know when the draft layout is ready to preview.",
    createdAt: "2026-09-02T14:35:00.000Z",
  },
  {
    id: "msg-101-2",
    requestId: "req-apex-101",
    organizationId: "org-apex-legal",
    authorId: "user-alex-staff",
    authorName: "Alex Morales",
    authorRole: "staff",
    body: "Thanks Sarah! We have received the assets and are building the responsive grid preview now. We aim to have the staging preview link ready for you by September 18.",
    createdAt: "2026-09-04T09:15:00.000Z",
  },
];

export const SEED_INTERNAL_NOTES = [
  {
    id: "note-101-1",
    requestId: "req-apex-101",
    organizationId: "org-apex-legal",
    authorId: "user-alex-staff",
    authorName: "Alex Morales",
    body: "Assets checked. Headshots are high-res WebP. Reusing the editorial partner card component from the practice directory.",
    createdAt: "2026-09-04T09:10:00.000Z",
  },
];

export const SEED_EVENTS: RequestEvent[] = [
  {
    id: "evt-101-1",
    requestId: "req-apex-101",
    organizationId: "org-apex-legal",
    actorId: "user-sarah-apex",
    actorName: "Sarah Jenkins",
    actorRole: "client_owner",
    eventType: "created",
    toStatus: "submitted",
    description: "Request submitted by Sarah Jenkins",
    timestamp: "2026-09-02T14:30:00.000Z",
  },
  {
    id: "evt-101-2",
    requestId: "req-apex-101",
    organizationId: "org-apex-legal",
    actorId: "user-alex-staff",
    actorName: "Alex Morales",
    actorRole: "staff",
    eventType: "status_changed",
    fromStatus: "submitted",
    toStatus: "in_progress",
    description: "Alex Morales scheduled and started work on request",
    timestamp: "2026-09-04T09:15:00.000Z",
  },
];
