import {defineArrayMember, defineField, defineType, type Rule} from "sanity";

import {publishingStatusOptions, validateCaseStudyReadiness, validateWorkIndexFeatured, validateWorkIndexRank} from "../objects/publishing";
import {proofClassifications} from "@/lib/proofClassification";
import {caseStudyEditorialGuidance} from "../editorialGuidance";

const requiredRichText = (rule: Rule) => rule.required().min(1);

export const caseStudy = defineType({
  name: "caseStudy",
  title: "Case study",
  type: "document",
  fields: [
    defineField({name: "title", title: "Internal record title", type: "string", validation: (rule) => rule.required()}),
    defineField({name: "seo", title: "SEO metadata", type: "seo"}),
    defineField({
      name: "publishingStatus",
      title: "Publishing readiness",
      type: "string",
      description: "Only Published ready case studies can appear on the public site. Complete proof, permissions, and image review before selecting it.",
      options: {list: publishingStatusOptions, layout: "radio"},
      initialValue: "draft",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {source: "title", maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "classification",
      title: "Classification",
      type: "string",
      description: "Required proof classification. This must remain visible wherever the work is presented.",
      options: {
        list: proofClassifications.map(({studioTitle, value}) => ({title: studioTitle, value})),
        layout: "radio",
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "projectIdentity",
      title: "Internal client / project identity",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "publicTitle",
      title: "Public case-study title",
      type: "string",
      description: "The title that can appear in search, links, and public case-study pages. Do not include a confidential client name.",
    }),
    defineField({
      name: "publicProjectIdentity",
      title: "Public client / project identity",
      type: "string",
      description: "Use an approved client or project name for real public work. Use an approved generic descriptor for confidential or white-label work, and a clear non-client descriptor for concept, prototype, or owned-brand work.",
    }),
    defineField({
      name: "publicSummary",
      title: "Public summary",
      type: "text",
      rows: 3,
      description: "A public-safe summary. Do not include confidential client identity, unapproved artifacts, or unsupported outcomes.",
    }),
    defineField({
      name: "publicRole",
      title: "Public Chromapages role",
      type: "string",
      description: "State Chromapages’ approved role in this engagement. Do not imply work outside the documented scope.",
    }),
    defineField({
      name: "publicIdentityApproved",
      title: "Public identity approved",
      type: "boolean",
      description: "Confirm that the public title and identity are accurate and permitted for the chosen classification.",
      initialValue: false,
    }),
    defineField({
      name: "publicArtifactApproved",
      title: "Public artifacts approved",
      type: "boolean",
      description: "Confirm that every image and artifact is permitted for public display under the chosen classification.",
      initialValue: false,
    }),
    defineField({
      name: "permissionStatus",
      title: "Permission / disclosure status",
      type: "string",
      description: "Record the public-display basis. Keep legal records outside this CMS field.",
      options: {
        list: [
          {title: "Not reviewed", value: "notReviewed"},
          {title: "Public client permission confirmed", value: "public-client-permission"},
          {title: "Confidential-work disclosure approved", value: "confidential-disclosure-approved"},
          {title: "White-label disclosure approved", value: "white-label-disclosure-approved"},
          {title: "Classification disclosure approved", value: "classification-disclosure-approved"},
        ],
        layout: "radio",
      },
      initialValue: "notReviewed",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "permissionNotes",
      title: "Permission review notes",
      type: "text",
      rows: 2,
      description: "Optional internal summary only. Do not include personal data, client contacts, or legal documents.",
    }),
    defineField({
      name: "proofReviewStatus",
      title: "Proof review",
      type: "string",
      description: "Confirm evidence, classification, claims, and attribution limitations against the proof policy.",
      options: {
        list: [
          {title: "Not reviewed", value: "notReviewed"},
          {title: "Approved", value: "approved"},
          {title: "Changes required", value: "changesRequired"},
        ],
        layout: "radio",
      },
      initialValue: "notReviewed",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "workIndexFeatured",
      title: "Feature in Selected Work",
      type: "boolean",
      description: "An editorial placement decision only. It does not indicate performance, client importance, or proof strength. At most one published-ready case study can be featured.",
      initialValue: false,
      validation: (rule) => rule.custom(validateWorkIndexFeatured),
    }),
    defineField({
      name: "workIndexRank",
      title: "Selected Work rank",
      type: "number",
      description: "A unique editorial display order. This controls sequence only; it is not a business-performance ranking.",
      validation: (rule) => rule.integer().positive().custom(validateWorkIndexRank),
    }),
    defineField({name: "description", title: "Description", type: "text", rows: 3}),
    defineField({name: "scope", title: "Scope", type: "blockContent", validation: requiredRichText}),
    defineField({name: "challenge", title: "Challenge", type: "blockContent", validation: requiredRichText}),
    defineField({name: "strategy", title: "Strategy", type: "blockContent", validation: requiredRichText}),
    defineField({name: "designDecisions", title: "Legacy design decisions", type: "blockContent", description: "Editorial source material retained during migration. Move approved public content into Build."}),
    defineField({name: "developmentDecisions", title: "Legacy development decisions", type: "blockContent", description: "Editorial source material retained during migration. Move approved public content into Build."}),
    defineField({name: "build", title: "04 / Build", type: "blockContent", description: "Explain the implemented design and engineering system as one coherent intervention.", validation: requiredRichText}),
    defineField({name: "launch", title: "05 / Launch", type: "blockContent", description: "Document approved QA, release, handoff, or operational readiness facts. Do not claim commercial impact without evidence.", validation: requiredRichText}),
    defineField({
      name: "evidence",
      title: "Legacy evidence notes",
      type: "blockContent",
      description: "Internal editorial source material retained during migration. Approved public evidence is rendered from Public proof hierarchy.",
    }),
    defineField({
      name: "proofSignals",
      title: "Public proof hierarchy",
      type: "array",
      description: "Add only verified public proof. The site prioritizes business outcome, client evidence, technical proof, process proof, then craft proof.",
      of: [defineArrayMember({type: "proofSignal"})],
    }),
    defineField({
      name: "attributionLimitations",
      title: "Attribution limitations",
      type: "text",
      rows: 4,
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "nextStage",
      title: "07 / Next Stage",
      type: "text",
      rows: 3,
      description: caseStudyEditorialGuidance.nextStage,
    }),
    defineField({
      name: "images",
      title: "Project media",
      type: "array",
      of: [defineArrayMember({type: "editorialImage"})],
      description: "Optional. Add only approved assets that explain the transformation; no device mockups, browser-window decoration, or visual filler.",
    }),
    defineField({
      name: "relatedServices",
      title: "Related services",
      type: "array",
      of: [defineArrayMember({type: "reference", to: [{type: "offer"}]})],
      validation: (rule) => rule.required().min(1),
    }),
  ],
  validation: (rule) => rule.custom(validateCaseStudyReadiness),
  preview: {
    select: {title: "title", classification: "classification", media: "images.0"},
    prepare: ({title, classification, media}) => ({title, subtitle: classification, media}),
  },
});
