import {defineArrayMember, defineField, defineType} from "sanity";

export const processPage = defineType({
  name: "processPage",
  title: "Process page",
  type: "document",
  fields: [
    defineField({name: "title", title: "Title", type: "string", validation: (rule) => rule.required()}),
    defineField({name: "seo", title: "SEO metadata", type: "seo"}),
    defineField({name: "introduction", title: "Introduction", type: "blockContent"}),
    defineField({
      name: "hero",
      title: "Hero section",
      description: "Header / hero section content for the How We Work / Process page.",
      type: "object",
      fields: [
        defineField({name: "eyebrow", title: "Eyebrow", type: "string", initialValue: "How We Work"}),
        defineField({name: "headline", title: "Headline", type: "string", description: "Main display heading on the page hero."}),
        defineField({name: "introduction", title: "Introduction", type: "text", rows: 3, description: "Supporting paragraph under the headline."}),
        defineField({name: "secondaryCtaLabel", title: "Secondary link label", type: "string", initialValue: "See the process →"}),
        defineField({name: "secondaryCtaHref", title: "Secondary link target", type: "string", initialValue: "#delivery-process"}),
        defineField({
          name: "image",
          title: "Hero image",
          type: "image",
          options: {hotspot: true},
          fields: [
            defineField({name: "alt", title: "Alternative text", type: "string"}),
            defineField({name: "caption", title: "Image caption / badge", type: "string"}),
          ],
        }),
      ],
    }),
    defineField({
      name: "steps",
      title: "Process steps",
      type: "array",
      of: [defineArrayMember({type: "processStep"})],
    }),
    defineField({name: "detail", title: "Supporting detail", type: "blockContent"}),
    defineField({name: "operatingPrinciplesIntro", title: "Operating principles introduction", description: "Optional replacement for the legacy supporting detail used above the operating-principles list.", type: "blockContent"}),
    defineField({name: "operatingPrinciples", title: "Operating principles", description: "Optional structured replacement for the numbered legacy supporting detail.", type: "array", of: [defineArrayMember({type: "differentiatorItem"})]}),
    defineField({
      name: "whyItMatters",
      title: "Why it matters section",
      description: "Common project risks / challenges and why a structured process is necessary.",
      type: "object",
      fields: [
        defineField({name: "eyebrow", title: "Eyebrow", type: "string", initialValue: "Why it matters"}),
        defineField({name: "headline", title: "Headline", type: "string", description: "Main display heading on the section."}),
        defineField({name: "introduction", title: "Introduction", type: "text", rows: 3, description: "Supporting paragraph under the headline."}),
        defineField({name: "ctaLabel", title: "Process link label", type: "string", initialValue: "See how the process prevents this →"}),
        defineField({name: "ctaHref", title: "Process link target", type: "string", initialValue: "#delivery-process"}),
        defineField({
          name: "items",
          title: "Risk / Challenge items",
          description: "Key project failure points or principles addressed by the process.",
          type: "array",
          of: [defineArrayMember({
            type: "object",
            name: "whyItMattersItem",
            title: "Item",
            fields: [
              defineField({name: "title", title: "Title", type: "string", validation: (rule) => rule.required()}),
              defineField({name: "description", title: "Description", type: "text", rows: 3, validation: (rule) => rule.required()}),
              defineField({
                name: "icon",
                title: "Icon",
                type: "image",
                fields: [
                  defineField({name: "alt", title: "Alternative text", type: "string"}),
                ],
              }),
            ],
            preview: {select: {title: "title", subtitle: "description"}},
          })],
        }),
      ],
    }),
    defineField({
      name: "workingTogether",
      title: "Working together section",
      description: "Roles, shared goals, and the responsibilities matrix on the How We Work / Process page.",
      type: "object",
      fields: [
        defineField({name: "eyebrow", title: "Eyebrow", type: "string", initialValue: "Working together"}),
        defineField({name: "headline", title: "Headline", type: "string", description: "Main display heading on the section."}),
        defineField({name: "introduction", title: "Introduction", type: "text", rows: 3, description: "Supporting paragraph under the headline."}),
        defineField({name: "ctaLabel", title: "Process link label", type: "string", initialValue: "See the delivery process →"}),
        defineField({name: "ctaHref", title: "Process link target", type: "string", initialValue: "#delivery-process"}),
        defineField({name: "sharedGoalLabel", title: "Shared goal label", type: "string", initialValue: "Same goal"}),
        defineField({name: "sharedGoalText", title: "Shared goal text", type: "text", rows: 2}),
        defineField({
          name: "roles",
          title: "Role columns",
          description: "The three column roles in the table: Studio, Client team, Together.",
          type: "array",
          of: [defineArrayMember({
            type: "object",
            name: "workingTogetherRole",
            title: "Role column",
            fields: [
              defineField({name: "label", title: "Role label", type: "string", validation: (rule) => rule.required()}),
              defineField({name: "detail", title: "Role description", type: "string"}),
              defineField({
                name: "icon",
                title: "Role icon",
                type: "image",
                fields: [
                  defineField({name: "alt", title: "Alternative text", type: "string"}),
                ],
              }),
            ],
            preview: {select: {title: "label", subtitle: "detail"}},
          })],
        }),
        defineField({
          name: "responsibilities",
          title: "Responsibilities matrix",
          description: "List of key responsibilities and who owns them (Studio, Client team, Together).",
          type: "array",
          of: [defineArrayMember({
            type: "object",
            name: "responsibilityRow",
            title: "Responsibility item",
            fields: [
              defineField({name: "title", title: "Title", type: "string", validation: (rule) => rule.required()}),
              defineField({name: "detail", title: "Detail / Description", type: "string"}),
              defineField({name: "studio", title: "Chromapages / Studio", type: "boolean", initialValue: false}),
              defineField({name: "team", title: "Your team / Client", type: "boolean", initialValue: false}),
              defineField({name: "together", title: "Together / Shared", type: "boolean", initialValue: false}),
            ],
            preview: {select: {title: "title", subtitle: "detail"}},
          })],
        }),
        defineField({name: "summaryTitle", title: "Summary title", type: "string", initialValue: "A stronger partnership"}),
        defineField({name: "summaryText", title: "Summary description", type: "string"}),
        defineField({name: "highlights", title: "Key highlights / badges", type: "array", of: [defineArrayMember({type: "string"})]}),
        defineField({name: "summaryCtaLabel", title: "Approach link label", type: "string", initialValue: "Our approach →"}),
        defineField({name: "summaryCtaHref", title: "Approach link target", type: "string", initialValue: "#operating-principles"}),
      ],
    }),
    defineField({
      name: "launchConfidence",
      title: "Launch confidence section",
      description: "Public launch-readiness copy and the four checklist areas on the How We Work page.",
      type: "object",
      fields: [
        defineField({name: "eyebrow", title: "Eyebrow", type: "string", validation: (rule) => rule.required()}),
        defineField({name: "headline", title: "Headline", type: "string", validation: (rule) => rule.required()}),
        defineField({name: "introduction", title: "Introduction", type: "text", rows: 3, validation: (rule) => rule.required()}),
        defineField({name: "checklistLabel", title: "Checklist label", type: "string", validation: (rule) => rule.required()}),
        defineField({name: "ctaLabel", title: "Checklist link label", type: "string", validation: (rule) => rule.required()}),
        defineField({
          name: "areas",
          title: "Checklist areas",
          description: "Keep all four areas. Their IDs select the matching site icon; drag to reorder them.",
          type: "array",
          of: [defineArrayMember({
            name: "launchArea",
            title: "Launch area",
            type: "object",
            fields: [
              defineField({name: "id", title: "Icon / stable ID", type: "string", options: {list: [
                {title: "Experience", value: "experience"},
                {title: "Customer action", value: "customer-action"},
                {title: "Technical release", value: "technical-release"},
                {title: "Handoff", value: "handoff"},
              ]}, validation: (rule) => rule.required()}),
              defineField({name: "title", title: "Title", type: "string", validation: (rule) => rule.required()}),
              defineField({name: "description", title: "Description", type: "text", rows: 3, validation: (rule) => rule.required()}),
              defineField({name: "checks", title: "Checks", type: "array", of: [defineArrayMember({type: "string"})], validation: (rule) => rule.required().min(1)}),
            ],
            preview: {select: {title: "title", subtitle: "id"}},
          })],
          validation: (rule) => rule.required().length(4),
        }),
      ],
    }),
    defineField({
      name: "afterLaunch",
      title: "After launch section",
      description: "The four-step improvement cycle shown after Launch Confidence on the How We Work page.",
      type: "object",
      fields: [
        defineField({name: "eyebrow", title: "Eyebrow", type: "string", validation: (rule) => rule.required()}),
        defineField({name: "headline", title: "Headline", type: "string", validation: (rule) => rule.required()}),
        defineField({name: "introduction", title: "Introduction", type: "text", rows: 4, validation: (rule) => rule.required()}),
        defineField({name: "repeatLabel", title: "Cycle ending label", type: "string", validation: (rule) => rule.required()}),
        defineField({
          name: "steps",
          title: "Improvement steps",
          description: "Drag to reorder. Keep all four steps so the cycle stays complete.",
          type: "array",
          of: [defineArrayMember({
            name: "afterLaunchStep",
            title: "After-launch step",
            type: "object",
            fields: [
              defineField({name: "id", title: "Stable ID", type: "string", validation: (rule) => rule.required().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)}),
              defineField({name: "title", title: "Title", type: "string", validation: (rule) => rule.required()}),
              defineField({name: "description", title: "Description", type: "text", rows: 3, validation: (rule) => rule.required()}),
              defineField({name: "output", title: "Output", type: "string", validation: (rule) => rule.required()}),
            ],
            preview: {select: {title: "title", subtitle: "output"}},
          })],
          validation: (rule) => rule.required().length(4),
        }),
      ],
    }),
    defineField({name: "cta", title: "Call to action", type: "callToAction"}),
  ],
  preview: {prepare: () => ({title: "Process page"})},
});
